## Quellenverzeichnis

[1] Quarks Dimension Ralph: *So steuern Bots deine Meinung | Quarks mit Marc-Uwe Kling*.  
YouTube.  
URL: https://www.youtube.com/watch?v=addZVkOTHZM  
Abruf: 07.09.2026.

[2] ...

[3] ...

[4] ...

[5] ...

[6] ...
